### ISSUE TITLE
ID

### ISSUE THREAD

**Issue by Ivanfinal** [Nitrax198/PruebaGit#7]
Mandame los ID y a que corresponde cada cosa

**Comment by Ivanfinal** [comment]
Miguel añade un Div oculto donde guardar el numero aleatorio

**Comment by Nitrax198** [comment]
Con hiden, con la propiedad visibiliti o cono display??

**Comment by Ivanfinal** [comment]
display lo veo mas comodo

**Comment by Nitrax198** [comment]
Pasame un croquis de paint de lo que necesitas, para que me haga una idea

**Comment by Nitrax198** [comment]
Necesitas que ponga un id para el botón de enviar??

**Comment by Ivanfinal** [comment]
Pon Id en todo

**Comment by Nitrax198** [comment]
ya he hecho mi parte, solo falta cambiar los nombres de los id y cosas por el estilo, según necesiteis los cambios id diciendomelo
